### ISSUE TITLE
routes with a trailing '/'

### ISSUE THREAD

**Issue by duhseekoh** [andrewrk/connect-proxy#21]
When a route is specified on the options, an extra / is added on the end. So the route specified is not actually matched with the request url if the request url doesn't contain a trailing / also. 

`var route = slashJoin(options.route, '');`
The line turns a specified route like `/api/endpointone`
into `/api/endpointone/`

So when the boolean check immediately below is ran on the requested url that we want to proxy its comparing:
`"/api/endpointone" === "/api/endpointone/"` which is obviously not true.

A realistic and valid use case is to be able to pass in a route with no trailing slash and expect that to match with requested urls with no trailing slash.

**Comment by amr** [comment]
Any chance this will be merged soon?

**Comment by andrewrk** [comment]
Not without a test case.

**Comment by andrewrk** [comment]
@amr looks like you're referring to @noahgrant's commit, which indeed has a test, and, in fact, has already been merged. I believe this issue is closed now.
