### ISSUE TITLE
Proxy exact URL

### ISSUE THREAD

**Issue by xcompass** [andrewrk/connect-proxy#27]
I'm trying to proxy a URL http://localhost/session. On the backend side, I got http://localhost/session/ (with a trailing slash). 

When I look at the test, I saw you have a "proxy exact URL":
https://github.com/andrewrk/connect-proxy/blob/master/test/test.js#L116

Isn't "exact URL" should be exact? e.g. http://localhost:8074/foo should proxy to http://localhost:8075/foo, not /foo/? Is it a bug? Thanks.

**Comment by andrewrk** [comment]
fixed with PR #26
